### ISSUE TITLE
[Feature request] Add easy way to install Pop!_OS with support for hibernation

### ISSUE THREAD

**Issue by feikedonia** [pop-os/iso#343] opened 2024-12-19 15:49 UTC
After some discursion on another feature request: 
https://github.com/pop-os/cosmic-epoch/issues/859

I wanted to ask if in the Pop!_OS iso / installer there can be added a way for users to conveniently install hibernation (suspend to disk) support without having to: 
* know it excists on Pop!_OS
* know / look up the exact steps to set it up
* having to run `systemctl hibernate` from the terminal.

Hibernation is a workflow and progress safer, most usefull to laptop-users. 
Hibernation support could be a selling point to use Pop!_OS instead of another distro, because of the convenience.

( I don't actually use the Pop!_OS installer, to know if this feature actually exists allready, but given the feature request 
 https://github.com/pop-os/cosmic-epoch/issues/859
it would very much surprise me )

**Comment by leviport** [comment] 2024-12-19 16:08
I believe this is a duplicate of https://github.com/pop-os/distinst/issues/171

**Comment by feikedonia** [comment] 2024-12-21 19:37
I'm sorry, I did search for hibernation in this repo, but not in outhers

**Closed** 2024-12-21 19:37 UTC

**Comment by leviport** [comment] 2024-12-23 16:13
No worries, it wasn't an easy one to find.
