### ISSUE TITLE
Clean Install - Changing Computer Name Causes Shell Commands to Lag

### ISSUE THREAD

**Issue by bashalarmist** [pop-os/iso#314] opened 2022-11-25 20:29 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
When you perform a fresh install of PopOS 

**Steps to reproduce (if you know):**
1. Install Pop OS
2. Go to settings > About 
3. Change device name
4. (Intermittent?) Run command with sudo, multiple second delay will occur before the command executes. 

**Expected behavior:**
There should be no delay.

**Other Notes:**
If you edit `/etc/hosts` and add the following line:
```127.0.1.1       [Computer Name]```
The issue will be resolved. Perhaps this should be automatic when changing the computer name.

**Comment by jacobgkau** [comment] 2022-11-25 21:23
Duplicate of https://github.com/pop-os/systemd/issues/5.

**Closed by jacobgkau** 2022-11-25 21:23 UTC
