### ISSUE TITLE
4k sector disks incorrectly calculated during installation

### ISSUE THREAD

**Issue by cblakely** [pop-os/iso#241] opened 2019-05-13 16:16 UTC
The 19.04 installer shows everything calculated as 512-byte blocks regardless of the actual disk configuration. For example a 400GB 4k-native disk shows up as 50GB. Parted correctly identifies the disk as 4096 block size, and show partitions as their correct size.

[screenshot from installer](https://imgur.com/dQV2oee)

**Comment by mmstick** [comment] 2019-05-13 16:21
Duplicate of https://github.com/pop-os/distinst/issues/177

**Closed by mmstick** 2019-05-13 16:21 UTC
