### ISSUE TITLE
Freeze on login, reboot, wake from suspend

### ISSUE THREAD

**Issue by igorbzin** [pop-os/iso#222] opened 2018-08-21 14:34 UTC
**Distribution (run `cat /etc/os-release`):
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description: OS freezes after signing in, rebooting or waking from suspend

**Steps to reproduce (if you know): Behaviour seems very random for waking from suspend, rebooting or shutting down always freezes the system, for login i enter the password once and it brings me after a gray screen back to login, after second attempt the system freezes

**Expected behavior:** Be able to reboot, wake from suspend or use login without the system freezing

**Other Notes:**
I have searched for many solutions, people were suggesting that the login freeze is due to a bad xorg.conf, though this bug i have bypassed by enabling automatically logging in at boot so i dont have to use the password and it boots every time. the login freeze occured even after a completely fresh install without any updating or installing of software. I am not able to reboot the system, the only way to shut down is a force shut down by holding the power button. Waking for suspend sometimes works but most of the time the screen is just black after opening up the lid, instead to wake up the system

**Comment by brs17** [comment] 2018-08-23 18:43
Duplicate of https://github.com/pop-os/pop/issues/341

**Closed by brs17** 2018-08-23 18:43 UTC
